### PR TITLE
A small cosmetic improvement for better readability.

### PR DESCRIPTION
**Pull request by MSIDoc**
A small cosmetic improvement for better readability.
This no longer shows the [houseID] but the name of the property. For the house owner, for an invitation for another player as well as for the guest key. 

**Here is a small example:**
```lua
-- currently:
-- Owner( 'playername' ) -> has key to property [houseID]
...
lib.registerContext(
     {   id = 'house_menu',
            title = Lang:t('housemenu.owner')..houseid,
... ...

-- new and better option 
-- Owner( 'playername' ) -> has key to the property [housename]
...
lib.registerContext(
     {   id = 'house_menu',
            title = Lang:t('housemenu.owner')..('\"')..Lang:t(('property.')..houseid))..('\"'),
... ...
```

The names for the properties with the corresponding [houseID] are read from the corresponding language module. For better readability, the name of the property has been placed in quotation marks.

### CODE REVIEW

**Comment by Andyauk** [comment]
> A small cosmetic improvement for better readability. This no longer shows the [houseID] but the name of the property. For the house owner, for an invitation for another player as well as for the guest key.
> 
> **Here is a small example:**
> 
> ```lua
> -- currently:
> -- Owner( 'playername' ) -> has key to property [houseID]
> ...
> lib.registerContext(
>      {   id = 'house_menu',
>             title = Lang:t('housemenu.owner')..houseid,
> ... ...
> 
> -- new and better option 
> -- Owner( 'playername' ) -> has key to the property [housename]
> ...
> lib.registerContext(
>      {   id = 'house_menu',
>             title = Lang:t('housemenu.owner')..('\"')..Lang:t(('property.')..houseid))..('\"'),
> ... ...
> ```
> 
> The names for the properties with the corresponding [houseID] are read from the corresponding language module. For better readability, the name of the property has been placed in quotation marks.

just checking this out. but you will need to make sure you merge with our latest copy. as you are a comment behind.

**Comment by MSIDoc** [comment]
> just checking this out. but you will need to make sure you merge with our latest copy. as you are a comment behind.

Thanks, you're welcome to do that 😁- but unfortunately the last commit is a merge of my pull request from my branch

**Comment by Andyauk** [comment]
> > just checking this out. but you will need to make sure you merge with our latest copy. as you are a comment behind.
> 
> Thanks, you're welcome to do that 😁- but unfortunately the last commit is a merge of my pull request from my branch

yes I know. but it conflicts' on the pull. is why you say do a pr. it gets accepted, then you need to pull yours again, to be up to date with the main. to then do the edits.

**Comment by Andyauk** [comment]
also there are a number of errors, please fix. so we can look over it. all the added

 `title = Lang:t('housemenu.owner')..('\"')..Lang:t(('property.')..houseid))..('\"'),`  and `title = Lang:t('housemenu.property')..('\"')..Lang:t(('property.')..houseid))..('\"'),`
`title = Lang:t('housemenu.guest_in')..('\"')..Lang:t(('property.')..houseid))..('\"'),`

are in incorrect format. when submitting a PR please check there's no errors from why you use to code.

**Comment by MSIDoc** [comment]
Oh, sorry, but thanks for pointing that out.
Habe den Fehler gefunden und behoben. Des weiteren habe ich bei der Lesbarkeit noch einen Zeilenumbruch eingefügt - siehe Bilder.
Screenshot 2023-12-31 115146
Screenshot 2023-12-31 120434
Screenshot 2023-12-31 120559
Screenshot 2023-12-31 120620

**Pull request merged**
